"""add observability fields to request_logs

Revision ID: d04e58aab30e
Revises: e15fcbc12025
Create Date: 2026-02-11 11:14:48.186526

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d04e58aab30e"
down_revision: Union[str, Sequence[str], None] = "e15fcbc12025"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
