"""add upstream_error_type to request_logs

Revision ID: d1b8099c8700
Revises: d04e58aab30e
Create Date: 2026-02-11 11:29:05.709605

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1b8099c8700"
down_revision: Union[str, Sequence[str], None] = "d04e58aab30e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "request_logs", sa.Column("upstream_error_type", sa.String(), nullable=True)
    )
    op.drop_column("request_logs", "error_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "request_logs",
        sa.Column("error_type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("request_logs", "upstream_error_type")
    # ### end Alembic commands ###
