"""add observability fields

Revision ID: e15fcbc12025
Revises:
Create Date: 2026-02-11 10:42:37.537651

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e15fcbc12025"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("request_logs", sa.Column("cache_status", sa.String(), nullable=True))
    op.add_column("request_logs", sa.Column("cache_key", sa.String(), nullable=True))
    op.add_column("request_logs", sa.Column("cache_ttl", sa.Integer(), nullable=True))
    op.add_column(
        "request_logs", sa.Column("circuit_state", sa.String(), nullable=True)
    )
    op.add_column(
        "request_logs", sa.Column("circuit_blocked", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "request_logs", sa.Column("upstream_service", sa.String(), nullable=True)
    )
    op.add_column(
        "request_logs", sa.Column("upstream_latency_ms", sa.Integer(), nullable=True)
    )
    op.add_column("request_logs", sa.Column("error_type", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_request_logs_api_key"), "request_logs", ["api_key"], unique=False
    )
    op.create_index(
        op.f("ix_request_logs_path"), "request_logs", ["path"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_logs_path"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_api_key"), table_name="request_logs")
    op.drop_column("request_logs", "error_type")
    op.drop_column("request_logs", "upstream_latency_ms")
    op.drop_column("request_logs", "upstream_service")
    op.drop_column("request_logs", "circuit_blocked")
    op.drop_column("request_logs", "circuit_state")
    op.drop_column("request_logs", "cache_ttl")
    op.drop_column("request_logs", "cache_key")
    op.drop_column("request_logs", "cache_status")
    # ### end Alembic commands ###
